name: Validate JSONs

on: [pull_request]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON with Glob
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: /schema/valid.json
          jsons: /json/classes_races.json,json/combat_chat.json,json/dialog.json,json/fishing.json,json/gestures_poses_icons.json,json/high_school_sim.json,json/items_1.json,json/items_2.json,json/items_3.json,json/items_4.json,json/items_5.json,json/items_6.json,json/items_7.json,json/items_8.json,json/locations.json,json/locations_continents.json,json/locations_misc.json,json/locations_short_names.json,json/login_screen.json,json/main_1.json,json/main_2.json,json/monster_descriptions_1.json,json/monster_descriptions_2.json,json/monster_descriptions_3.json,json/monster_descriptions_4.json,json/monster_descriptions_5.json,json/monster_descriptions_6.json,json/monster_descriptions_7.json,json/monsters_maybe.json,json/more_descriptions.json,json/random.json,json/save_dialog.json,json/skill_tree_1.json,json/skill_tree_2.json,json/skill_tree_3.json,json/spell_list_and_descriptions.json,json/story_quest_names.json,json/tbd_not_sure.json
